---
abstract: 'Scanner for L<Text::Xslate> style file'
author:
  - 'Kazuhiro Osawa, Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Localizer-Scanner-Xslate
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Localizer::Scanner::Xslate:
    file: lib/Localizer/Scanner/Xslate.pm
    version: 0.01
requires:
  Localizer: 0
  Text::Xslate: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/Localizer-Scanner-Xslate/issues
  homepage: https://github.com/tokuhirom/Localizer-Scanner-Xslate
  repository: git://github.com/tokuhirom/Localizer-Scanner-Xslate.git
version: 0.01
